<?php
/**
 *
 * @author  R. Dale Owen   @mediotype
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<script type="text/javascript">
    //<![CDATA[
    //traditional magento checkout is billing, shipping, shipping options, payment
    $$('#co-shipping-method-form .button').each(function(item){
        item.originonclick = item.onclick;
        item.onclick = function() {
            var shipOption = $$('#co-shipping-method-form input[checked=checked]');
            ga('ec:setAction', 'checkout_option', {
                'step': 3,
                'option': shipOption[0].value
            });
            item.onclick = item.originonclick;
            ga('send', 'event', 'Checkout', 'Option',{
                'hitCallback': function() {
                    item.click(item.originonclick);
                }
            });
        }
    });
    //]]>
</script>