<?php
/**
 *
 * @author  R. Dale Owen   @mediotype
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<script type="text/javascript">
    //<![CDATA[
<?php foreach($this->getItems() as $item): ?>
    <?php $product = $item->getProduct() ?>
    ga('ec:addProduct', {
        'id': '<?php echo $product->getId(); ?>',
        'name': '<?php echo $product->getName(); ?>',
        <?php if($product->getManufacturer()): ?>
        'brand': '<?php echo $product->getManufacturer() ?>',
        <?php endif; ?>
        'price': '<?php echo $item->getPrice(); ?>',
        'quantity': '<?php echo $item->getQty() ?>'
    });

<?php endforeach ?>
    //]]>
</script>